### ISSUE TITLE
Create Eat & Drink page

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#15]
Put all the eat and drink listings currently under the "Entertainment" anchor link on a separate page called "Eat & Drink" and update link in nav menu of site.

**Comment by kayiwa** [comment]
this feels like a design decision which are dependent on an external volunteer @librarianchase I can't control when they will get to these. If you have design ability I urge you to do them and submit a PR.

**Comment by kayiwa** [comment]
ping @alexandradm ☝️

**Comment by librarianchase** [comment]
Yes, this was what the committee decided about the design during the Jan. 31 meeting, modeled after the [Pittsburgh proposal site](https://code4lib2020.library.cmu.edu/) that has separate pages. That's why we organized our web copy in Box around separate pages. Once everyone had a chance to view the site and we discussed during the Feb. 7 meeting, they still preferred the original decision to structure the site with pages over anchors. Hope this clarifies. I don't know how to use this to design a site. It's not a tool I've ever used. @kayiwa

**Comment by alexandradm** [comment]
it requires a new theme template, basically a redesign of the entire html and design structure. i will submit a new template on Tuesday, but that will round out the available volunteer hours I have for this project

**Comment by kayiwa** [comment]
The Pittsburgh one is powered by a Drupal Content Management System. 
```
c4lbuffaloproposal.github.io master % http http://code4lib2020.library.cmu.edu/
HTTP/1.1 200 OK
Cache-Control: no-cache, must-revalidate
Connection: Keep-Alive
Content-Language: en
Content-Type: text/html; charset=utf-8
Date: Fri, 21 Feb 2020 18:03:43 GMT
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Keep-Alive: timeout=5, max=100
Link: </node/1>; rel="shortlink",</pittsburgh>; rel="canonical"
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Generator: Drupal 7 (http://drupal.org)
X-Powered-By: PHP/5.4.16

<!DOCTYPE html>
<html lang="en" dir="ltr"
```

**Comment by librarianchase** [comment]
> 
> 
> The Pittsburgh one is powered by a Drupal Content Management System.
> 
> ```
> c4lbuffaloproposal.github.io master % http http://code4lib2020.library.cmu.edu/
> HTTP/1.1 200 OK
> Cache-Control: no-cache, must-revalidate
> Connection: Keep-Alive
> Content-Language: en
> Content-Type: text/html; charset=utf-8
> Date: Fri, 21 Feb 2020 18:03:43 GMT
> Expires: Sun, 19 Nov 1978 05:00:00 GMT
> Keep-Alive: timeout=5, max=100
> Link: </node/1>; rel="shortlink",</pittsburgh>; rel="canonical"
> Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16
> Transfer-Encoding: chunked
> X-Content-Type-Options: nosniff
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-Generator: Drupal 7 (http://drupal.org)
> X-Powered-By: PHP/5.4.16
> 
> <!DOCTYPE html>
> <html lang="en" dir="ltr"
> ```

@alexandradm I know it's built on Drupal, but my committee members just selected that structure, meaning separate pages over anchor links. They don't know about CMSs. They just looked at a bunch of example proposal sites I posted for them in Box, between our Jan. 7 and Jan. 31 meetings, and a consensus was reached to have pages over anchors.

**Comment by alexandradm** [comment]
Added. Francis was just sharing with you that Drupal, as a CMS, makes it easy to add new pages, but has costs to run. GH pages and straight HTML/CSS, while free, has coding overhead.

**Comment by kayiwa** [comment]
thanks for the PR @alexandradm I'll incorporate and close the rest of the issues here. I think we are even on beers now.
