### ISSUE TITLE
Create "About" page

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#16]
Move copy currently in the "About" anchor link section of page to a new page called "About" and update link in nav menu.

**Comment by kayiwa** [comment]
this feels like a design decision which are dependent on an external volunteer @librarianchase I can't control when they will get to these. If you have design ability I urge you to do them and submit a PR.

**Comment by kayiwa** [comment]
ping @alexandradm ☝️

**Comment by alexandradm** [comment]
added
