### ISSUE TITLE
Create "Venues" page

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#18]
Take copy/content under Venues section of "How to get here, where to stay" anchor link section of home page and move to new "Venues" page. Headings on new "Venues" page are:

1. University at Buffalo (where we'll enter copy about the location of the conference sessions)
2. Reception (where we'll enter copy about the reception location)
3. Hotels (where we'll list hotels and prices that Jenn from Concentra delivers to me)

Update link in nav menu of site.

**Comment by kayiwa** [comment]
this feels like a design decision which are dependent on an external volunteer @librarianchase I can't control when they will get to these. If you have design ability I urge you to do them and submit a PR.

**Comment by kayiwa** [comment]
ping @alexandradm ☝️

**Comment by alexandradm** [comment]
added.
