### ISSUE TITLE
Create "Transportation" page

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#19]
Move the following sections and their content from the current "How to get here, where to stay" anchor link section from home page to new "Transportation" page and update link in nav menu of site.:

1. Transportation
2. Airport to Hotel
3. Campus Parking and Shuttles
4. Downtown Buffalo

**Comment by kayiwa** [comment]
this feels like a design decision which are dependent on an external volunteer @librarianchase I can't control when they will get to these. If you have design ability I urge you to do them and submit a PR.

**Comment by kayiwa** [comment]
ping @alexandradm ☝️

**Comment by alexandradm** [comment]
added.
