### ISSUE TITLE
Create "Financials" page

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#20]
Take copy/content from "Financials" anchor link section and move to new "Financials" page and update nav menu.

**Comment by kayiwa** [comment]
this feels like a design decision which are dependent on an external volunteer @librarianchase I can't control when they will get to these. If you have design ability I urge you to do them and submit a PR.

**Comment by kayiwa** [comment]
ping @alexandradm ☝️

**Comment by alexandradm** [comment]
added
