### ISSUE TITLE
Navigation menu order

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#21]
1. Home (Why Buffalo copy)
2. Financials
3. Venues
4. Transportation
5. Eat & Drink
6. Attractions
7. About

I'm just spit-balling this order; maybe the other committee members will comment.

**Comment by kayiwa** [comment]
this feels like a design decision which are dependent on an external volunteer @librarianchase I can't control when they will get to these. If you have design ability I urge you to do them and submit a PR.

**Comment by kayiwa** [comment]
ping @alexandradm ☝️

**Comment by alexandradm** [comment]
please have the committee choose the final order, and then I will adjust.

**Comment by kayiwa** [comment]
this is currently done as described above.

**Comment by mkicey** [comment]
@librarianchase Your order looks good, although depending on the actual content of "About" I would be inclined to make that #2 and move the other items down the list by one. But @alexandradm is likely right that this should be a topic for brief committee discussion.

**Comment by kayiwa** [comment]
going with @mkicey order as described here.
