### ISSUE TITLE
Transportation section

### ISSUE THREAD

**Issue by cmklotzb** [kayiwa/c4lbuffaloproposal#25]
Transportation finishing touches depends on the venue and hotels we select.

In the meantime, can we complete the small section below on the site:
"NFTA's Metro Rail provides a direct line from UB's South Campus to downtown Canalside. From metro stops, it's just a quick walk to many of Buffalo's entertainment and dining options. "

Potential images: 
https://commons.wikimedia.org/wiki/File:Main_Street_in_Buffalo_NY_with_light_rail_and_Shea%27s_Performing_Arts_Center_(2015).jpg
https://commons.wikimedia.org/wiki/File:Theater_Station_at_Sheas.jpg
https://commons.wikimedia.org/wiki/File:20150827_61_NFTA_Light_Rail_at_Fountain_Plaza_(21990211710).jpg
https://commons.wikimedia.org/wiki/File:Buffalo_light_rail_train_laying_over_at_Erie_Canal_Harbor_station_(2015).jpg

**Comment by kayiwa** [comment]
I'm sorry @cmklotzb I am not sure I understand what you mean on "the small section below on the site" Important to remember "completeness" will be done by a different group of folks, so no one reading the proposal brochure expects the decision on where the venue will be to be included. Compare for example [the proposal for Pittsburgh](https://code4lib2020.library.cmu.edu/transportation) and the [Pittsburgh actual conference](https://2020.code4lib.org/general-info/venues/)

**Comment by kayiwa** [comment]
Never mind @cmklotzb I see what you mean now.
