### ISSUE TITLE
Transportation section image

### ISSUE THREAD

**Issue by cmklotzb** [kayiwa/c4lbuffaloproposal#40]
Image Credit: David Wilson on [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Main_Street_in_Buffalo_NY_with_light_rail_and_Shea%27s_Performing_Arts_Center_(2015).jpg)

![Main_Street_in_Buffalo_NY_with_light_rail_and_Shea's_Performing_Arts_Center_(2015)](https://user-images.githubusercontent.com/61332576/75564793-c93ba400-5a1a-11ea-910a-58c0654aba4c.jpg)

**Comment by kayiwa** [comment]
heya @cmklotzb is this in addition to? or replacing?
