### ISSUE TITLE
get the keep buffalo secret image. 

### ISSUE THREAD

**Issue by kayiwa** [kayiwa/c4lbuffaloproposal#5]
currently using a screenshot of this image
also get it positioned better.

**Comment by librarianchase** [comment]
OK, found it on [Buffalo Rising](https://www.buffalorising.com/2019/10/buffalo-keeping-it-real/).

**Comment by librarianchase** [comment]
We need permission from Buffalo Rising for the photograph at least. The photo is also a picture of another copyrighted work, the artwork by Ian de Beer and Jake The Sign Guy.

**Comment by librarianchase** [comment]
Someone with a good camera could take their own shot, which would cut the permissions in half.

**Comment by librarianchase** [comment]
Permission emails (PDF would be best) from Ian de Beer and Jake The Sign Guy can be deposited in the [image-permission-letters](https://buffalo.app.box.com/folder/103801688100) Box directory.
