### ISSUE TITLE
Problem with mobile view of site

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#89]
@kayiwa Sent URL to Evviva to give her the good news it was done, but this is what it looked like in Chrome on her phone:
![2020-03-05-mobile-chrome](https://user-images.githubusercontent.com/25646750/76036717-dc66dc00-5f12-11ea-9db9-48af447be70c.jpg)

**Comment by librarianchase** [comment]
Update: I've checked all the pages of the site, and the only pages that don't display in mobile are the home page and the financials page.

Different issue on the financials page. The only thing wrong on that page is the footer floats in the middle as you scroll up and down the page.

**Comment by kayiwa** [comment]
this @librarianchase is a side effect of moving from single page app to multi page landing. The fix won't come easy. All attempts I have done thus far have made it worse and this remains the sanest look. If you are comfortable with CSS have a go at it.

**Comment by librarianchase** [comment]
@kayiwa The only change in display is that the footer is now pinned to the middle of the page for Home page and Financials page in *mobile view*. So there's something with the footer on these two pages. Maybe look at the other pages where it displays correctly? I don't know CSS.

**Comment by Blake-** [comment]
I'll have a look as well. @librarianchase is this all Chrome iPhone? Looks like this on my iPhone. 
(Asking because I bet more people use Safari and it looks fine on Safari on iPhone)

**Comment by Blake-** [comment]
@kayiwa not sure what you've tried so far, would something like this do it?

```
img {
  display: block
}
@media (min-width: 650px) {
  img {
    display: none
  }
}
```

**Comment by librarianchase** [comment]
@Blake- I don't know what kind of phone Evviva has, but I'm pretty sure Kicey has an iPhone, and it displayed the same way for him. Displays the same way on my Samsung in both Firefox Focus and the Samsung browser.

**Comment by Blake-** [comment]
@kayiwa @librarianchase 
2 PRs in for this so far. 
For the images... the images just go away on small screens. Not sure if that's the best fix, but it did the job.

**Comment by kayiwa** [comment]
🎉 Thanks @Blake-
