### ISSUE TITLE
Change request: pages over anchors

### ISSUE THREAD

**Issue by librarianchase** [kayiwa/c4lbuffaloproposal#9]
When the committee met today, we all agreed we'd prefer pages over anchor links with a horizontal tabbed navigation menu similar to what's at the top of the site now, but not anchor links, links to separate pages.
- We'd also like a page called "Venues", and the three headings of copy are University at Buffalo, Reception, Hotels.

Thanks!

**Comment by kayiwa** [comment]
I'll be breaking this up into two issues to manage my sanity @librarianchase

**Comment by librarianchase** [comment]
> 
> 
> I'll be breaking this up into two issues to manage my sanity @librarianchase

OK, but my original change request was lost somehow. The separate "Venues" page has 3 sections: University at Buffalo, Reception, and Hotels.

So it's not a change of heading from Hotels to Venues.
