### ISSUE TITLE
Fix on Financials page

### ISSUE THREAD

**Issue by mkicey** [kayiwa/c4lbuffaloproposal#91]
The text at the bottom of the right column runs into the black footer.

(I am viewing the page on Chrome 80.0.3987.132 64-bit.)

**Comment by librarianchase** [comment]
Now the footer is pinned further up the page for *desktop view*. (Don't know if this is related to the *mobile view* issue with the footer on the Financials page.)

(I am viewing the page on Firefox 68.0.1 and Chrome 78.0.3904.87.)

**Comment by kayiwa** [comment]
fixed by @Blake- PR https://github.com/kayiwa/c4lbuffaloproposal/pull/94
